ALTER TABLE Users
DROP CONSTRAINT PK_Users

ALTER TABLE Users
ADD CONSTRAINT PK_Users PRIMARY KEY(Id)

ALTER TABLE Users
ADD CONSTRAINT CH_Username CHECK(LEN(Username) >= 3)

ALTER TABLE Users
ADD CONSTRAINT UN_Username UNIQUE(Username)