CREATE DATABASE SoftUni

USE Softuni

CREATE TABLE Towns (
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL,
)

CREATE TABLE Adresses (
Id INT PRIMARY KEY IDENTITY,
AdressText NVARCHAR(30) NOT NULL,
TownId INT FOREIGN KEY REFERENCES Towns(Id) NOT NULL
)

CREATE TABLE Departments (
Id INT PRIMARY KEY IDENTITY,
[Name] NVARCHAR(30) NOT NULL,
)

CREATE TABLE Employees (
Id INT IDENTITY,
FirstName NVARCHAR(30) NOT NULL,
MiddleName NVARCHAR(30),
LastName NVARCHAR(30) NOT NULL,
JobTitle NVARCHAR(20) NOT NULL,
DepartmentId INT NOT NULL,
HireDate DATETIME NOT NULL,
Salary DECIMAL(15,2) NOT NULL,
AddressId INT
)

ALTER TABLE Employees
ADD CONSTRAINT PK_Employees PRIMARY KEY(Id);

ALTER TABLE Employees
ADD CONSTRAINT FK_Department FOREIGN KEY(DepartmentId) REFERENCES Departments(Id);

ALTER TABLE Employees
ADD CONSTRAINT FK_Address FOREIGN KEY(AddressId) REFERENCES Adresses(Id)
